In [20]:
# impoertin the deprndies
import numpy as np
import pandas as pd
import re 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [21]:
import nltk 
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\PC\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [22]:
#print(stopwords.words('run'))

loading the data sets

In [23]:
df=pd.read_csv(r"C:\Users\PC\Downloads\archive (10).zip")
df.head(10)

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
5,6903,"Tehran, USA","\nI’m not an immigrant, but my grandparents ...",FAKE
6,7341,Girl Horrified At What She Watches Boyfriend D...,"Share This Baylee Luciani (left), Screenshot o...",FAKE
7,95,‘Britain’s Schindler’ Dies at 106,A Czech stockbroker who saved more than 650 Je...,REAL
8,4869,Fact check: Trump and Clinton at the 'commande...,Hillary Clinton and Donald Trump made some ina...,REAL
9,2909,Iran reportedly makes new push for uranium con...,Iranian negotiators reportedly have made a las...,REAL

In [24]:
df.shape

(6335, 4)

In [25]:
df=df.replace({'label':{'FAKE':0,'REAL':1}},)

C:\Users\PC\AppData\Local\Temp\ipykernel_3792\320339415.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace({'label':{'FAKE':0,'REAL':1}},)

In [27]:
df.head(10)

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",0
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,0
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,1
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",0
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,1
5,6903,"Tehran, USA","\nI’m not an immigrant, but my grandparents ...",0
6,7341,Girl Horrified At What She Watches Boyfriend D...,"Share This Baylee Luciani (left), Screenshot o...",0
7,95,‘Britain’s Schindler’ Dies at 106,A Czech stockbroker who saved more than 650 Je...,1
8,4869,Fact check: Trump and Clinton at the 'commande...,Hillary Clinton and Donald Trump made some ina...,1
9,2909,Iran reportedly makes new push for uranium con...,Iranian negotiators reportedly have made a las...,1

In [29]:
# marging the auther name and news titlel
df.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [40]:
# merging the authoe name and news title
df['content']=df['title']
print(df['content'])

0                            You Can Smell Hillary’s Fear
1       Watch The Exact Moment Paul Ryan Committed Pol...
2             Kerry to go to Paris in gesture of sympathy
3       Bernie supporters on Twitter erupt in anger ag...
4        The Battle of New York: Why This Primary Matters
                              ...
6330    State Department says it can't find emails fro...
6331    The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332    Anti-Trump Protesters Are Tools of the Oligarc...
6333    In Ethiopia, Obama seeks progress on peace, se...
6334    Jeb Bush Is Suddenly Attacking Trump. Here's W...
Name: content, Length: 6335, dtype: object

In [41]:
# sprating the data & label
x=df.drop(columns='label',axis=1)
y=df['label']

In [42]:
print(x)
print(y)

      Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...
2           3608        Kerry to go to Paris in gesture of sympathy
3          10142  Bernie supporters on Twitter erupt in anger ag...
4            875   The Battle of New York: Why This Primary Matters
...          ...                                                ...
6330        4490  State Department says it can't find emails fro...
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...
6333        4021  In Ethiopia, Obama seeks progress on peace, se...
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...

                                                   text  \
0     Daniel Greenfield, a Shillman Journalism Fello...
1     Google Pinterest Digg Linkedin Reddit Stumbleu...
2     U.S. Secretary of State John F. Kerry said Mon...
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...
4     It's primary day in New York and front-runners...
...                                                 ...
6330  The State Department told the Republican Natio...
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332   Anti-Trump Protesters Are Tools of the Oligar...
6333  ADDIS ABABA, Ethiopia —President Obama convene...
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...

                                                content
0                          You Can Smell Hillary’s Fear
1     Watch The Exact Moment Paul Ryan Committed Pol...
2           Kerry to go to Paris in gesture of sympathy
3     Bernie supporters on Twitter erupt in anger ag...
4      The Battle of New York: Why This Primary Matters
...                                                 ...
6330  State Department says it can't find emails fro...
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332  Anti-Trump Protesters Are Tools of the Oligarc...
6333  In Ethiopia, Obama seeks progress on peace, se...
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...

[6335 rows x 4 columns]
0       0
1       0
2       1
3       0
4       1
       ..
6330    1
6331    0
6332    0
6333    1
6334    1
Name: label, Length: 6335, dtype: int64

In [62]:
# steeming :
# it the prosees of reducing a word to its root word
port_stem=PorterStemmer()
def stemming(content):
    steem_content=re.sub('[^a-zA-Z]',' ',str(content))
    steem_content=steem_content.lower()
    steem_content=steem_content.split()
    steem_content=[port_stem.stem(word) for word in steem_content if not word in stopwords.words('english')]
    steem_content=' '.join(steem_content)
    return steem_content

In [63]:
df['content']=df['content'].apply(stemming)
print(df['content'])

0                                 youcansmellhillarysfear
1       watchtheexactmomentpaulryancommittedpoliticals...
2                     kerrytogotoparisingestureofsympathi
3       berniesupportersontwittereruptinangeragainstth...
4                    thebattleofnewyorkwhythisprimarymatt
                              ...
6330    statedepartmentsaysitcantfindemailsfromclinton...
6331         thepinpbsshouldstandforplutocraticorpentagon
6332      antitrumpprotestersaretoolsoftheoligarchyinform
6333    inethiopiaobamaseeksprogressonpeacesecurityine...
6334      jebbushissuddenlyattackingtrumphereswhythatmatt
Name: content, Length: 6335, dtype: object

In [119]:
# speratting the dataat and labelx
x=df['content'].values
y=df['label'].values

In [120]:
print(x)

['youcansmellhillarysfear'
 'watchtheexactmomentpaulryancommittedpoliticalsuicideatatrumprallyvideo'
 'kerrytogotoparisingestureofsympathi' ...
 'antitrumpprotestersaretoolsoftheoligarchyinform'
 'inethiopiaobamaseeksprogressonpeacesecurityineastafrica'
 'jebbushissuddenlyattackingtrumphereswhythatmatt']

In [121]:
print(y)

[0 0 1 ... 0 1 1]

In [122]:
y.shape

(6335,)

In [123]:
x.shape

(6335,)

In [124]:
# convert text datat into numerical dtaat
vectorizer=TfidfVectorizer()
vectorizer.fit(x)

x=vectorizer.transform(x)
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6333 stored elements and shape (6335, 6213)>
  Coords	Values
  (0, 6192)	1.0
  (1, 5748)	1.0
  (2, 2842)	1.0
  (3, 430)	1.0
  (4, 4742)	1.0
  (5, 4696)	1.0
  (6, 1869)	1.0
  (7, 593)	1.0
  (8, 1616)	1.0
  (9, 2545)	1.0
  (10, 6126)	1.0
  (11, 1394)	1.0
  (12, 4576)	1.0
  (13, 5750)	1.0
  (14, 5434)	1.0
  (15, 2380)	1.0
  (16, 4433)	1.0
  (17, 2095)	1.0
  (18, 5848)	1.0
  (19, 4756)	1.0
  (20, 5035)	1.0
  (21, 1526)	1.0
  (22, 2104)	1.0
  (23, 3346)	1.0
  (24, 2464)	1.0
  :	:
  (6310, 2597)	1.0
  (6311, 4753)	1.0
  (6312, 24)	1.0
  (6313, 1332)	1.0
  (6314, 4068)	1.0
  (6315, 3782)	1.0
  (6316, 1380)	1.0
  (6317, 1696)	1.0
  (6318, 542)	1.0
  (6319, 6026)	1.0
  (6320, 3410)	1.0
  (6321, 2957)	1.0
  (6322, 3969)	1.0
  (6323, 420)	1.0
  (6324, 77)	1.0
  (6325, 6112)	1.0
  (6326, 1311)	1.0
  (6327, 1939)	1.0
  (6328, 3991)	1.0
  (6329, 283)	1.0
  (6330, 4535)	1.0
  (6331, 4961)	1.0
  (6332, 202)	1.0
  (6333, 2463)	1.0
  (6334, 2718)	1.0

In [125]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [126]:
model=LogisticRegression()

In [127]:
model.fit(x_train,y_train)

LogisticRegression()

In [128]:
train_dat_pred=model.predict(x_train)
acc_on_train_data=accuracy_score(train_dat_pred,y_train)

In [129]:
print(acc_on_train_data)

0.999605367008682

In [130]:
test_data_ored=model.predict(x_test)
acc_on_test_dat=accuracy_score(y_test,test_data_ored)

In [131]:
print(acc_on_test_dat)

0.5169692186266772

In [132]:
# thats not good
print(x_test[30])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1 stored elements and shape (1, 6213)>
  Coords	Values
  (0, 3472)	1.0

In [133]:
x_new = x_test[30]

prediction = model.predict(x_new)
print(prediction)

if (prediction[0]==0):
  print('The news is fake')
else:
  print('The news is real')

[1]
The news is real