In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
# data collexction and priprocrsing
df=pd.read_csv("C:/Users/PC/Downloads/mail_data (1).csv")
df.head(20)

   Category                                            Message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
5      spam  FreeMsg Hey there darling it's been 3 week's n...
6       ham  Even my brother is not like to speak with me. ...
7       ham  As per your request 'Melle Melle (Oru Minnamin...
8      spam  WINNER!! As a valued network customer you have...
9      spam  Had your mobile 11 months or more? U R entitle...
10      ham  I'm gonna be home soon and i don't want to tal...
11     spam  SIX chances to win CASH! From 100 to 20,000 po...
12     spam  URGENT! You have won a 1 week FREE membership ...
13      ham  I've been searching for the right words to tha...
14      ham                I HAVE A DATE ON SUNDAY WITH WILL!!
15     spam  XXXMobileMovieClub: To use your credit, click ...
16      ham                         Oh k...i'm watching here:)
17      ham  Eh u remember how 2 spell his name... Yes i di...
18      ham  Fine if thats the way u feel. Thats the way ...
19     spam  England v Macedonia - dont miss the goals/team...

In [3]:
df.shape

(5572, 2)

In [4]:
# replecing null value with null string
df1=df.where((pd.notnull(df)),'')

In [5]:
print(df1)

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
df.head(199)

    Category                                            Message
0        ham  Go until jurong point, crazy.. Available only ...
1        ham                      Ok lar... Joking wif u oni...
2       spam  Free entry in 2 a wkly comp to win FA Cup fina...
3        ham  U dun say so early hor... U c already then say...
4        ham  Nah I don't think he goes to usf, he lives aro...
..       ...                                                ...
194      ham  It will stop on itself. I however suggest she ...
195      ham  How are you doing? Hope you've settled in for ...
196      ham                       Gud mrng dear hav a nice day
197      ham                       Did u got that persons story
198      ham  is your hamster dead? Hey so tmr i meet you at...

[199 rows x 2 columns]

In [7]:
df.loc[1:100]

    Category                                            Message
1        ham                      Ok lar... Joking wif u oni...
2       spam  Free entry in 2 a wkly comp to win FA Cup fina...
3        ham  U dun say so early hor... U c already then say...
4        ham  Nah I don't think he goes to usf, he lives aro...
5       spam  FreeMsg Hey there darling it's been 3 week's n...
..       ...                                                ...
96       ham                  Watching telugu movie..wat abt u?
97       ham  i see. When we finish we have loads of loans t...
98       ham  Hi. Wk been ok - on hols now! Yes on for a bit...
99       ham                    I see a cup of coffee animation
100      ham  Please don't text me anymore. I have nothing e...

[100 rows x 2 columns]

In [8]:
df1.head(22)

   Category                                            Message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
5      spam  FreeMsg Hey there darling it's been 3 week's n...
6       ham  Even my brother is not like to speak with me. ...
7       ham  As per your request 'Melle Melle (Oru Minnamin...
8      spam  WINNER!! As a valued network customer you have...
9      spam  Had your mobile 11 months or more? U R entitle...
10      ham  I'm gonna be home soon and i don't want to tal...
11     spam  SIX chances to win CASH! From 100 to 20,000 po...
12     spam  URGENT! You have won a 1 week FREE membership ...
13      ham  I've been searching for the right words to tha...
14      ham                I HAVE A DATE ON SUNDAY WITH WILL!!
15     spam  XXXMobileMovieClub: To use your credit, click ...
16      ham                         Oh k...i'm watching here:)
17      ham  Eh u remember how 2 spell his name... Yes i di...
18      ham  Fine if thats the way u feel. Thats the way ...
19     spam  England v Macedonia - dont miss the goals/team...
20      ham          Is that seriously how you spell his name?
21      ham    I‘m going to try for 2 months ha ha only joking

In [9]:
df1.replace({'Category':{'ham':1,'spam':0}},inplace=True)
df1.head()

C:\Users\PC\AppData\Local\Temp\ipykernel_7636\1507593405.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1.replace({'Category':{'ham':1,'spam':0}},inplace=True)

   Category                                            Message
0         1  Go until jurong point, crazy.. Available only ...
1         1                      Ok lar... Joking wif u oni...
2         0  Free entry in 2 a wkly comp to win FA Cup fina...
3         1  U dun say so early hor... U c already then say...
4         1  Nah I don't think he goes to usf, he lives aro...

In [10]:
x=df1['Message']
y=df1['Category']

In [11]:
print(x)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [12]:
print(y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: int64

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [14]:
print(x.shape)
print(x_test.shape)
print(y_test.shape)
print(x_train.shape)

(5572,)
(1115,)
(1115,)
(4457,)

In [15]:
print(x.shape)
print(y.shape)

(5572,)
(5572,)

In [16]:
print(x_train)
print(x_train.shape)

3075                  Don know. I did't msg him recently.
1787    Do you know why god created gap between your f...
1614                         Thnx dude. u guys out 2nite?
4304                                      Yup i'm free...
3266    44 7732584351, Do you want a New Nokia 3510i c...
                              ...
789     5 Free Top Polyphonic Tones call 087018728737,...
968     What do u want when i come back?.a beautiful n...
1667    Guess who spent all last night phasing in and ...
3321    Eh sorry leh... I din c ur msg. Not sad alread...
1688    Free Top ringtone -sub to weekly ringtone-get ...
Name: Message, Length: 4457, dtype: object
(4457,)

# feature actraction

In [17]:
# transform the test data to feature vector that can used as input to te logistic regration
feature_extration=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)
x_train_feature=feature_extration.fit_transform(x_train)
x_test_feature=feature_extration.transform(x_test)

# convert y_train and y test values  as integir
y_train=y_train.astype('int')
y_test=y_test.astype('int')

In [18]:
print(x_train_feature)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34775 stored elements and shape (4457, 7431)>
  Coords	Values
  (0, 2329)	0.38783870336935383
  (0, 3811)	0.34780165336891333
  (0, 2224)	0.413103377943378
  (0, 4456)	0.4168658090846482
  (0, 5413)	0.6198254967574347
  (1, 3811)	0.17419952275504033
  (1, 3046)	0.2503712792613518
  (1, 1991)	0.33036995955537024
  (1, 2956)	0.33036995955537024
  (1, 2758)	0.3226407885943799
  (1, 1839)	0.2784903590561455
  (1, 918)	0.22871581159877646
  (1, 2746)	0.3398297002864083
  (1, 2957)	0.3398297002864083
  (1, 3325)	0.31610586766078863
  (1, 3185)	0.29694482957694585
  (1, 4080)	0.18880584110891163
  (2, 6601)	0.6056811524587518
  (2, 2404)	0.45287711070606745
  (2, 3156)	0.4107239318312698
  (2, 407)	0.509272536051008
  (3, 7414)	0.8100020912469564
  (3, 2870)	0.5864269879324768
  (4, 2870)	0.41872147309323743
  (4, 487)	0.2899118421746198
  :	:
  (4454, 2855)	0.47210665083641806
  (4454, 2246)	0.47210665083641806
  (4455, 4456)	0.24920025316220423
  (4455, 3922)	0.31287563163368587
  (4455, 6916)	0.19636985317119715
  (4455, 4715)	0.30714144758811196
  (4455, 3872)	0.3108911491788658
  (4455, 7113)	0.30536590342067704
  (4455, 6091)	0.23103841516927642
  (4455, 6810)	0.29731757715898277
  (4455, 5646)	0.33545678464631296
  (4455, 2469)	0.35441545511837946
  (4455, 2247)	0.37052851863170466
  (4456, 2870)	0.31523196273113385
  (4456, 5778)	0.16243064490100795
  (4456, 334)	0.2220077711654938
  (4456, 6307)	0.2752760476857975
  (4456, 6249)	0.17573831794959716
  (4456, 7150)	0.3677554681447669
  (4456, 7154)	0.24083218452280053
  (4456, 6028)	0.21034888000987115
  (4456, 5569)	0.4619395404299172
  (4456, 6311)	0.30133182431707617
  (4456, 647)	0.30133182431707617
  (4456, 141)	0.292943737785358

In [19]:
# trainging meachine learing model
model=LogisticRegression()

In [20]:
model.fit(x_train_feature,y_train)

LogisticRegression()

In [21]:
# evoluting the trainend model
#1 pridiction training dtaa
x_train_pridiction=model.predict(x_train_feature)
trining_dtaa_accuracy=accuracy_score(x_train_pridiction,y_train)
print('accuarcy on training data: ', trining_dtaa_accuracy)

accuarcy on training data:  0.9676912721561588

In [23]:
# pridiction on test data
x_test_pridiction=model.predict(x_test_feature)
testing_data_accuracy=accuracy_score(y_test,x_test_pridiction)
print('aaccuracy on test data: ',testing_data_accuracy)

aaccuracy on test data:  0.9668161434977578

In [52]:
input_mail=["FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv"

]
input_data_feature=feature_extration.transform(input_mail)
pridiction=model.predict(input_data_feature)
print(pridiction)
if pridiction==[1] :
    print('it is not spam')
else:
    print('it is spam')

[1]
it is not spam